"""empty message

Revision ID: 0965688b687a
Revises: cdbf41aea838
Create Date: 2019-08-20 16:22:25.220048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0965688b687a'
down_revision = 'cdbf41aea838'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('description', sa.String(length=255), nullable=True))
    op.add_column('candidates', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('candidates', sa.Column('political_party', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidates', 'political_party')
    op.drop_column('candidates', 'number')
    op.drop_column('candidates', 'description')
    op.drop_column('candidates', 'age')
    # ### end Alembic commands ###
